name: avahi
version: 0.0.0-dev.2

description:
  Provides a client to connect to Avahi - the service that implements mDNS/DNS-SD on Linux.

homepage: https://github.com/canonical/avahi.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.4.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
