name: avahi
version: 0.1.0

description:
  Provides a client to connect to Avahi - the service that implements mDNS/DNS-SD on Linux.

homepage: https://github.com/canonical/avahi.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
